# Generated by Django 6.0.3 on 2026-03-26 17:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("question", models.CharField(max_length=500)),
                ("signal_id", models.CharField(db_index=True, max_length=100)),
                ("metric", models.CharField(blank=True, default="", max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("config_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("on_true_transition", "When condition becomes true"),
                            ("every_true", "Every time condition is true"),
                            ("on_false_transition", "When condition becomes false"),
                        ],
                        default="on_true_transition",
                        max_length=30,
                    ),
                ),
                (
                    "cooldown_hours",
                    models.PositiveIntegerField(
                        default=24,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("delivery_channels", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("last_result", models.BooleanField(blank=True, null=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
                ("last_explanation", models.TextField(blank=True, default="")),
                ("last_values_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("result", models.BooleanField(blank=True, db_index=True, null=True)),
                ("explanation", models.TextField(blank=True, default="")),
                ("values_json", models.JSONField(blank=True, default=dict)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("was_triggered", models.BooleanField(db_index=True, default=False)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alert_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["user", "status", "is_active"],
                name="alerts_aler_user_id_e48f8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["signal_id", "is_active"], name="alerts_aler_signal__263d98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["frequency", "is_active"], name="alerts_aler_frequen_0f5ee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["alert_rule", "evaluated_at"],
                name="alerts_aler_alert_r_fd017f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["was_triggered", "evaluated_at"],
                name="alerts_aler_was_tri_578fcc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["result", "evaluated_at"], name="alerts_aler_result_3b8966_idx"
            ),
        ),
    ]
