from __future__ import annotations

from typing import Dict, List, Tuple

ROUTE_MAP = {
    "managed_money_net_percentile_156w": [
        "managed money percentile",
        "managed money extreme",
        "managed money positioning percentile",
        "managed money percentile 156w",
    ],
    "managed_money_net": [
        "managed money net",
        "net managed money",
        "spec net length",
        "managed money positioning",
        "cot managed money net",
        "cftc managed money net",
    ],
    "managed_money_long": [
        "managed money long",
        "spec longs",
        "cftc longs",
    ],
    "managed_money_short": [
        "managed money short",
        "spec shorts",
        "cftc shorts",
    ],
    "open_interest": [
        "open interest",
        "cftc open interest",
        "cot open interest",
    ],
    "des_special_questions_text": [
        "dallas fed special questions",
        "special questions",
        "survey special questions",
    ],
    "des_comments_text": [
        "survey comments",
        "des comments",
        "dallas fed comments",
        "respondent comments",
    ],
    "des_report_summary_text": [
        "dallas fed energy survey",
        "energy survey",
        "oil and gas survey",
        "current report",
        "latest survey summary",
    ],
    "des_business_activity_index": [
        "business activity index",
        "dallas fed business activity",
        "des business activity",
    ],
    "des_company_outlook_index": [
        "company outlook",
        "company outlook index",
    ],
    "des_outlook_uncertainty_index": [
        "uncertainty index",
        "outlook uncertainty",
    ],
    "des_oil_production_index": [
        "oil production index",
        "des oil production",
    ],
    "des_gas_production_index": [
        "gas production index",
        "natural gas production index",
        "des gas production",
    ],
    "des_capex_index": [
        "capex index",
        "capital expenditures index",
        "capital expenditure index",
    ],
    "des_employment_index": [
        "employment index",
        "des employment",
    ],
    "des_input_cost_index": [
        "input cost index",
        "input costs",
    ],
    "des_finding_development_costs_index": [
        "finding and development costs",
        "development costs index",
    ],
    "des_lease_operating_expense_index": [
        "lease operating expense",
        "lease operating expenses",
    ],
    "des_prices_received_services_index": [
        "prices received services",
        "prices received for services",
    ],
    "des_equipment_utilization_index": [
        "equipment utilization",
        "utilization of equipment",
    ],
    "des_operating_margin_index": [
        "operating margin",
        "operating margin index",
    ],
    "des_wti_price_expectation_1y": [
        "wti expectations",
        "wti price expectations",
        "wti 1 year",
        "wti one year",
        "price expectations",
    ],
    "des_hh_price_expectation_1y": [
        "henry hub expectations",
        "henry hub price expectations",
        "hh expectations",
        "henry hub 1 year",
    ],
    "des_breakeven_oil_us": [
        "break-even oil",
        "breakeven oil",
        "oil breakeven",
    ],
    "des_breakeven_gas_us": [
        "break-even gas",
        "breakeven gas",
        "gas breakeven",
    ],
    "iso_gas_dependency": [
        "gas share",
        "gas dependency",
        "percentage of electricity generation",
        "percent of electricity generation",
        "what percentage of electricity generation",
        "electricity generation from natural gas",
        "share of electricity from natural gas",
        "grid gas",
        "gas burn",
        "gas-fired",
        "fuel mix",
        "generation mix",
        "power mix",
        "dispatch",
        "how much gas generation",
    ],
    "iso_renewables": [
        "renewables",
        "renewable generation",
        "renewable share",
        "wind and solar",
        "wind solar",
        "solar and wind",
        "wind generation",
        "solar generation",
    ],
    "iso_fuel_mix": [
        "fuel mix",
        "generation mix",
        "power mix",
        "by fuel",
        "gas wind solar",
    ],
    "iso_load": [
        "load",
        "demand",
        "electric demand",
        "power demand",
        "system demand",
    ],
    "working_gas_storage_change_weekly": [
        "storage change",
        "weekly storage change",
        "week over week storage",
        "storage wow",
        "storage build",
        "storage injection",
        "storage withdrawal",
        "build",
        "net injection",
        "net withdrawal",
        "change in storage",
    ],
    "working_gas_storage_lower48": [
        "storage",
        "inventory",
        "working gas",
        "injection",
        "withdrawal",
    ],
    "henry_hub_spot": [
        "henry hub",
        "spot price",
        "gas price",
        "benchmark price",
    ],
    "lng_exports": [
        "lng exports",
        "lng export",
        "lng export capacity",
        "lng capacity utilization",
        "export capacity",
        "imports vs exports",
        "import vs export",
        "export vs import",
        "import and export",
        "which regions import vs export",
        "export lng",
        "liquefied natural gas export",
        "gas exports",
        "pipeline exports",
        "pipeline flow",
        "gas flow",
        "pipeline throughput",
    ],
    "lng_imports": [
        "lng imports",
        "import lng",
        "liquefied natural gas import",
        "gas imports",
        "pipeline imports",
    ],
    "ng_consumption_lower48": [
        "consumption",
        "consumes",
        "usage",
    ],
    "ng_consumption_by_sector": [
        "sector consumption",
        "consumption by sector",
        "end use",
        "residential",
        "commercial",
        "industrial",
        "electric power",
        "power sector",
        "which sector",
    ],
    "ng_electricity": [
        "electricity",
        "power plants",
        "power generation",
        "power burn",
        "natural gas power burn",
        "gas power burn",
    ],
    "ng_production_lower48": ["production", "output", "supply", "dry gas production"],
    "ng_supply_balance_regime": [
        "gas supply",
        "natural gas supply",
        "supply expanding",
        "supply tightening",
        "expanding or tightening",
        "tightening or expanding",
        "market tightening",
        "market balance",
        "supply-demand balance",
        "supply demand balance",
        "fundamentals",
        "supply constrained",
        "tightening",
        "loosening",
    ],
    "ng_exploration_reserves_lower48": [
        "exploration",
        "reserves",
        "proved reserves",
    ],
    "ng_pipeline": [
        "pipeline projects",
        "pipeline project",
        "pipeline capacity",
        "state to state capacity",
        "major pipeline",
        "pipeline summary",
        "inflow by region",
        "inflow by state",
        "outflow by region",
        "outflow by state",
        "historical projects",
    ],
    "weather_degree_days_forecast_vs_5y": [
        "degree day",
        "degree days",
        "weather forecast",
        "weather-related demand",
        "weather demand",
        "seasonal norm",
        "seasonal norms",
        "seasonal normal",
        "seasonal normals",
        "bullish",
        "bearish",
        "hdd",
        "cdd",
        "heating degree",
        "cooling degree",
        "1-year average",
        "2-year average",
        "3-year average",
        "4-year average",
        "vs 5-year",
        "vs 5 year",
        "five-year average",
        "5-year average",
        "year average",
        "weather normal",
    ],
    "weather_regional_demand_drivers": [
        "which regions are driving",
        "regions driving weather-related demand",
        "regional weather demand",
        "weather demand by region",
        "weather drivers by region",
    ],
}

NORMALIZE_PATTERNS: List[Tuple[str, str]] = [
    (r"[–—]", "-"),
    (r"\blower forty[- ]?eight\b", "lower 48"),
    (r"\bnat gas\b", "natural gas"),
    (r"\bdraw\b", "withdrawal"),
    (r"\bwithdrawals\b", "withdrawal"),
    (r"\binjections\b", "injection"),
    (r"\bstorage build\b", "storage injection"),
    (r"\bbuild in storage\b", "storage injection"),
    (r"\bgrid mix\b", "fuel mix"),
    (r"\bpower mix\b", "fuel mix"),
    (r"\bstack\b", "fuel mix"),
    (r"\bclean energy\b", "renewables"),
    (r"\bgreen power\b", "renewables"),
    (r"\brenewable penetration\b", "renewable share"),
    (r"\bgas burn\b", "gas-fired generation"),
    (r"\belectric-sector\b", "electricity"),
    (r"\bcash gas\b", "spot price"),
]

# metric-specific bonus terms
BONUS_TERMS: Dict[str, List[str]] = {
    "managed_money_net_percentile_156w": ["managed money", "percentile", "cftc", "cot"],
    "managed_money_net": ["managed money", "net", "cftc", "cot"],
    "managed_money_long": ["managed money", "long", "cftc", "cot"],
    "managed_money_short": ["managed money", "short", "cftc", "cot"],
    "open_interest": ["open interest", "cftc", "cot"],
    "des_special_questions_text": ["special questions", "des", "dallas fed"],
    "des_comments_text": ["comments", "survey comments", "des"],
    "des_report_summary_text": ["energy survey", "dallas fed", "des"],
    "des_business_activity_index": ["business activity", "des", "dallas fed"],
    "des_company_outlook_index": ["company outlook", "des"],
    "des_outlook_uncertainty_index": ["uncertainty", "des"],
    "des_oil_production_index": ["oil production", "des"],
    "des_gas_production_index": ["gas production", "des"],
    "des_capex_index": ["capex", "capital expenditures", "des"],
    "des_wti_price_expectation_1y": ["wti", "expectations", "des"],
    "des_hh_price_expectation_1y": ["henry hub", "expectations", "des"],
    "des_breakeven_oil_us": ["breakeven", "oil", "des"],
    "des_breakeven_gas_us": ["breakeven", "gas", "des"],
    "working_gas_storage_change_weekly": [
        "last week",
        "weekly",
        "wow",
        "build",
        "injection",
        "withdrawal",
    ],
    "working_gas_storage_lower48": ["storage", "inventory", "working gas"],
    "henry_hub_spot": ["henry hub", "spot", "benchmark"],
    "lng_exports": ["exports", "export", "pipeline flow", "throughput"],
    "lng_imports": ["imports", "import"],
    "ng_consumption_lower48": ["consumption", "usage"],
    "ng_consumption_by_sector": [
        "sector",
        "residential",
        "commercial",
        "industrial",
        "electric power",
        "power",
    ],
    "ng_electricity": [
        "power plants",
        "electricity",
        "power generation",
        "power burn",
        "gas power burn",
    ],
    "ng_production_lower48": ["production", "output", "supply"],
    "ng_supply_balance_regime": [
        "gas supply",
        "market balance",
        "fundamentals",
        "tightening",
        "loosening",
        "supply constrained",
    ],
    "ng_exploration_reserves_lower48": ["reserves", "exploration"],
    "ng_pipeline": ["pipeline", "capacity", "projects", "inflow", "outflow"],
    "weather_degree_days_forecast_vs_5y": [
        "weather",
        "forecast",
        "seasonal",
        "norm",
        "bullish",
        "bearish",
        "demand",
        "hdd",
        "cdd",
        "degree day",
        "5-year",
        "normal",
    ],
    "weather_regional_demand_drivers": [
        "regions",
        "regional",
        "driving",
        "weather",
        "demand",
    ],
    "iso_load": ["load", "demand", "system demand"],
    "iso_gas_dependency": [
        "gas share",
        "gas-fired",
        "gas-fired generation",
        "percentage",
        "percent",
        "generation",
    ],
    "iso_renewables": ["renewables", "wind", "solar"],
    "iso_fuel_mix": ["fuel mix", "by fuel", "generation mix"],
}

COMPARE_PATTERNS = [r"\bcompare\b", r"\bversus\b", r"\bvs\b"]
RANK_PATTERNS = [
    r"\bhighest\b",
    r"\blowest\b",
    r"\bmost\b",
    r"\bleast\b",
    r"\bwhich region\b",
    r"\bfastest\b",
]
DERIVED_PATTERNS = [
    r"\bnet exporter\b",
    r"\bbalance\b",
    r"\bversus normal\b",
    r"\btight\b",
]
EXPLAIN_PATTERNS = [r"\bwhy\b", r"\bbecause\b", r"\bdid .* rise\b", r"\bdid .* fall\b"]
FORECAST_PATTERNS = [
    r"\bforecast\b",
    r"\bprojection\b",
    r"\bproject\b",
    r"\bprojected\b",
    r"\bnext week\b",
    r"\bnext 7 days\b",
    r"\bnext 14 days\b",
    r"\bnext two weeks\b",
    r"\bnext 2 weeks\b",
]
